
import java.awt.Color;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author raimo
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
     private Tdesk tdesk = new Tdesk(); 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogin = new javax.swing.JPanel();
        loginjLabel1 = new javax.swing.JLabel();
        jTextFieldLoginEmail = new javax.swing.JTextField();
        loginjLabel2 = new javax.swing.JLabel();
        jPasswordFieldLogin = new javax.swing.JPasswordField();
        jToggleButtonLogin = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        loginjLabel3 = new javax.swing.JLabel();
        loginjLabel4 = new javax.swing.JLabel();
        loginjLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelImageOfLogin = new javax.swing.JLabel();
        jPanelSettings = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jLabelSettings = new javax.swing.JLabel();
        jLabelSettings1 = new javax.swing.JLabel();
        jLabelSettings3 = new javax.swing.JLabel();
        jLabelSettings2 = new javax.swing.JLabel();
        jLabelSettings4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(null);

        jPanelLogin.setMaximumSize(new java.awt.Dimension(700, 700));
        jPanelLogin.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanelLogin.setPreferredSize(new java.awt.Dimension(700, 700));
        jPanelLogin.setLayout(null);

        loginjLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loginjLabel1.setText("EL. Paštas: ");
        jPanelLogin.add(loginjLabel1);
        loginjLabel1.setBounds(170, 90, 130, 50);

        jTextFieldLoginEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTextFieldLoginEmail.setForeground(new java.awt.Color(204, 0, 255));
        jTextFieldLoginEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(204, 0, 204)));
        jTextFieldLoginEmail.setCaretColor(new java.awt.Color(204, 0, 255));
        jTextFieldLoginEmail.setDisabledTextColor(new java.awt.Color(0, 51, 204));
        jTextFieldLoginEmail.setMaximumSize(new java.awt.Dimension(380, 60));
        jTextFieldLoginEmail.setMinimumSize(new java.awt.Dimension(380, 60));
        jTextFieldLoginEmail.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldLoginEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldLoginEmailKeyReleased(evt);
            }
        });
        jPanelLogin.add(jTextFieldLoginEmail);
        jTextFieldLoginEmail.setBounds(170, 140, 380, 60);

        loginjLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loginjLabel2.setText("Slaptažodis:");
        jPanelLogin.add(loginjLabel2);
        loginjLabel2.setBounds(170, 200, 130, 50);

        jPasswordFieldLogin.setText("jPasswordField1");
        jPasswordFieldLogin.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 0, 255)));
        jPasswordFieldLogin.setMaximumSize(new java.awt.Dimension(380, 60));
        jPasswordFieldLogin.setMinimumSize(new java.awt.Dimension(380, 60));
        jPanelLogin.add(jPasswordFieldLogin);
        jPasswordFieldLogin.setBounds(170, 250, 380, 60);

        jToggleButtonLogin.setBackground(new java.awt.Color(255, 0, 255));
        jToggleButtonLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jToggleButtonLogin.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButtonLogin.setText("Prisijungti");
        jToggleButtonLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.pink, java.awt.Color.pink, java.awt.Color.pink, java.awt.Color.pink));
        jToggleButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonLoginActionPerformed(evt);
            }
        });
        jPanelLogin.add(jToggleButtonLogin);
        jToggleButtonLogin.setBounds(260, 350, 210, 60);

        jLabel1.setText(" Guest Mode");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanelLogin.add(jLabel1);
        jLabel1.setBounds(330, 430, 70, 20);

        loginjLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fb.png"))); // NOI18N
        loginjLabel3.setMaximumSize(new java.awt.Dimension(50, 50));
        loginjLabel3.setMinimumSize(new java.awt.Dimension(50, 50));
        loginjLabel3.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanelLogin.add(loginjLabel3);
        loginjLabel3.setBounds(270, 500, 50, 50);

        loginjLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/twitter.jpg"))); // NOI18N
        jPanelLogin.add(loginjLabel4);
        loginjLabel4.setBounds(340, 500, 50, 50);

        loginjLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/google ++.png"))); // NOI18N
        jPanelLogin.add(loginjLabel5);
        loginjLabel5.setBounds(410, 500, 50, 50);

        jLabel2.setText(" RĄSTAI");
        jPanelLogin.add(jLabel2);
        jLabel2.setBounds(340, 590, 50, 20);

        jLabel3.setText("2019");
        jPanelLogin.add(jLabel3);
        jLabel3.setBounds(350, 620, 30, 20);

        jLabelImageOfLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Login.jpg"))); // NOI18N
        jLabelImageOfLogin.setMaximumSize(new java.awt.Dimension(700, 700));
        jLabelImageOfLogin.setMinimumSize(new java.awt.Dimension(700, 700));
        jLabelImageOfLogin.setPreferredSize(new java.awt.Dimension(700, 700));
        jPanelLogin.add(jLabelImageOfLogin);
        jLabelImageOfLogin.setBounds(0, 0, 700, 700);

        getContentPane().add(jPanelLogin);
        jPanelLogin.setBounds(0, 0, 700, 700);

        jPanelSettings.setForeground(new java.awt.Color(255, 255, 255));
        jPanelSettings.setMaximumSize(new java.awt.Dimension(700, 700));
        jPanelSettings.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanelSettings.setLayout(null);

        jSlider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jSlider1MouseReleased(evt);
            }
        });
        jPanelSettings.add(jSlider1);
        jSlider1.setBounds(40, 170, 610, 22);

        jLabelSettings.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSettings.setText("Riškumas");
        jPanelSettings.add(jLabelSettings);
        jLabelSettings.setBounds(290, 130, 110, 30);

        jLabelSettings1.setText("0");
        jPanelSettings.add(jLabelSettings1);
        jLabelSettings1.setBounds(20, 170, 10, 13);

        jLabelSettings3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelSettings3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSettings3.setText("Nustatymai");
        jPanelSettings.add(jLabelSettings3);
        jLabelSettings3.setBounds(290, 60, 130, 30);

        jLabelSettings2.setText("100");
        jPanelSettings.add(jLabelSettings2);
        jLabelSettings2.setBounds(650, 170, 31, 13);

        jLabelSettings4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/settings.jpg"))); // NOI18N
        jPanelSettings.add(jLabelSettings4);
        jLabelSettings4.setBounds(250, 60, 37, 30);

        jLabel4.setBackground(new java.awt.Color(255, 0, 255));
        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/violet.png"))); // NOI18N
        jPanelSettings.add(jLabel4);
        jLabel4.setBounds(0, 0, 700, 100);

        getContentPane().add(jPanelSettings);
        jPanelSettings.setBounds(0, 0, 700, 700);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldLoginEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLoginEmailKeyReleased
           this.jPasswordFieldLogin.setText("");
            
            if(!this.isValidEmail(this.jTextFieldLoginEmail.getText()))
                this.jTextFieldLoginEmail.setBackground(Color.RED);
            else
                 this.jTextFieldLoginEmail.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTextFieldLoginEmailKeyReleased

    private void jToggleButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonLoginActionPerformed
       
        if(this.tdesk.chLogin( this.jTextFieldLoginEmail.getText(),  String.valueOf(jPasswordFieldLogin.getPassword())))
                this.setVisible(1);
    }//GEN-LAST:event_jToggleButtonLoginActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
                this.setVisible(1);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jSlider1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseReleased
             try{  this.setBrightness(this.jSlider1.getValue());} 
              catch(IOException ex){}
    }//GEN-LAST:event_jSlider1MouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelImageOfLogin;
    private javax.swing.JLabel jLabelSettings;
    private javax.swing.JLabel jLabelSettings1;
    private javax.swing.JLabel jLabelSettings2;
    private javax.swing.JLabel jLabelSettings3;
    private javax.swing.JLabel jLabelSettings4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelSettings;
    private javax.swing.JPasswordField jPasswordFieldLogin;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextFieldLoginEmail;
    private javax.swing.JToggleButton jToggleButtonLogin;
    private javax.swing.JLabel loginjLabel1;
    private javax.swing.JLabel loginjLabel2;
    private javax.swing.JLabel loginjLabel3;
    private javax.swing.JLabel loginjLabel4;
    private javax.swing.JLabel loginjLabel5;
    // End of variables declaration//GEN-END:variables
   
    private static boolean isValidEmail(String emailAddress) {
    return emailAddress.contains(" ") == false && emailAddress.matches(".+@.+\\.[a-z]+");
   }
   
    private void  setVisible(int i){
        
        this.jPanelLogin.setVisible(false);
        this.jPanelSettings.setVisible(false);
        if(i==0)
              this.jLabelImageOfLogin.setVisible(true);
        if(i==1)
           this.jPanelSettings.setVisible(true);
    }
    
     private static void setBrightness(int brightness)
            throws IOException {
        //Creates a powerShell command that will set the brightness to the requested value (0-100), after the requested delay (in milliseconds) has passed. 
        String s = String.format("$brightness = %d;", brightness)
                + "$delay = 0;"
                + "$myMonitor = Get-WmiObject -Namespace root\\wmi -Class WmiMonitorBrightnessMethods;"
                + "$myMonitor.wmisetbrightness($delay, $brightness)";
        String command = "powershell.exe  " + s;
        // Executing the command
        Process powerShellProcess = Runtime.getRuntime().exec(command);

        powerShellProcess.getOutputStream().close();

        //Report any error messages
        String line;

        BufferedReader stderr = new BufferedReader(new InputStreamReader(
                powerShellProcess.getErrorStream()));
        line = stderr.readLine();
        if (line != null)
        {
            //System.err.println("Standard Error:");
            do
            {
                //System.err.println(line);
            } while ((line = stderr.readLine()) != null);

        }
        stderr.close();

    }
}
